spring:
  application:
    name: SHOPPING-CART-SERVICE
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: false

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
