spring:
  application:
    name: PRODUCT-CATALOG-SERVICE
  data:
    rest:
      base-path: api
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
