spring:
  application:
    name: PRODUCT-CATALOG-SERVICE
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8081
